kind: Service
apiVersion: v1
metadata:
  name: my-frontend-service
  labels:
    app: my-frontend-service
spec:
   ports:
    - port: 8082
      targetPort: 80
      nodePort: 31200
   selector:
     app: my-frontend 
     type: LoadBalancer